FROM node:20-alpine 

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install 

# Copy application files
COPY . .

# Expose port
EXPOSE 8000
CMD [ "npm", "start" ]
# RUN chmod +x /app/entrypoint.sh
# ENTRYPOINT ["/app/entrypoint.sh"]

